#please do not edit this file
import calculator

def testAdd():
    assert (calculator.add(0,3) == 3)
    assert (calculator.add(5,0) == 5)
    assert (calculator.add(-1,-7) == -8)
    assert (calculator.add(-8,3) == -5)
    
def testSubtract():
    assert (calculator.subtract(0,3) == -3)
    assert (calculator.subtract(5,0) == 5)
    assert (calculator.subtract(-1,-7) == 6)
    assert (calculator.subtract(-8,3) == -11)

def testMultiply():
    assert (calculator.multiply(0,3) == 0)
    assert (calculator.multiply(5,0) == 0)
    assert (calculator.multiply(-1,-7) == 7)
    assert (calculator.multiply(-8,3) == -24)
    assert (calculator.multiply(8,3) == 24)

def testDivide():
    assert (calculator.divide(-1,-7) == 1/7)
    assert (calculator.divide(-8,3) == -8/3)
    assert (calculator.divide(8,3) == 8/3)
    assert (calculator.divide(0,3) == 0)
    try:
        calculator.divide(5,0)
    except Exception as err:
        assert (str(err) == 'I\'m sorry, I can\'t divide by zero')
    